### ISSUE TITLE
create function to predicted biomass against DBH, by species

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#73] opened 2019-03-12 14:38 UTC
@maurolepore,

In order to check current calculations, and for future users to be able to visualize what allodb is giving in terms of predicted biomass, we'll want to make the following plot type:
x-axis: DBH (cm)
y-axis: biomass (kg)
one colored line or series of points for each species at a site, spanning the range of sizes observed at the site

**Comment by maurolepore** [comment] 2019-03-12 15:08
Thanks! 

>  spanning the range of sizes observed at the site

How would you cut the dhb range for each species? Say, in 3 bins?

``` r
dbh_species1 <- c(11.1, 11.3, 15, 25.8, 25.9, 27, 30.1, 33)

ggplot2::cut_number(dbh_species1, 5)
#> [1] [11.1,12.8] [11.1,12.8] (12.8,23.6] (23.6,26.1] (23.6,26.1] (26.1,28.9]
#> [7] (28.9,33]   (28.9,33]  
#> Levels: [11.1,12.8] (12.8,23.6] (23.6,26.1] (26.1,28.9] (28.9,33]
```

Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by teixeirak** [comment] 2019-03-12 18:06
We don't want to bin sizes-- just display a continuous linear function of biomass as a function of DBH. It could be a scatter plot or a line plot of the equation. I'm including an example of how I'd expect this to look for SCBI, with the modification that I'd like a separate color for each species + legend.

![scbi_Allometries](https://user-images.githubusercontent.com/6355854/54224400-cf660700-44cf-11e9-8895-999f637ae6ce.png)

**Comment by maurolepore** [comment] 2019-03-13 15:00
Here are two plots similar to what you describe, except that here I'm not using species names but species codes. Notice that agb is the one that comes with the dataset -- not the one we calculate. That'll come a little later.

ALTERNATIVE 1

![image](https://user-images.githubusercontent.com/5856545/54289097-f92a3700-457e-11e9-8f46-08840a34add4.png)

ALTERNATIVE 2

![image](https://user-images.githubusercontent.com/5856545/54289217-2840a880-457f-11e9-9c7b-11b1efe7e102.png)

![image](https://user-images.githubusercontent.com/5856545/54289260-35f62e00-457f-11e9-9154-aaf5a580c448.png)

**Comment by teixeirak** [comment] 2019-03-13 15:58
I'd actually like to have both. The first is valuable for picking out anomolies, the second for seeing what's going on with each species.

**Comment by teixeirak** [comment] 2019-03-13 21:30
Another note on this— option 1 should be the first one that users would see. Option 2 is if they want to dig in more.

**Comment by maurolepore** [comment] 2019-03-14 15:27
@teixeirak and @gonzalezeb,

Here is an article exploring `dbh` vs. `biomass` (compared to `dbh` vs. `agb`). Please review and comment if this makes sense. 

Notice that we still lack some features that should produce better results. For example, For each row in a census dataset, the code currently sums the biomass for all equaitons associated to it (based on site and species). This should be correct except when the mulitple equations refer not to different parts of a tree but refer to trees of different diameter. We still don't handle dbh-specific equations.

Also, some species have no value and I'll be exploring why.

**Comment by maurolepore** [comment] 2019-03-14 15:31
BTW,

* I don't think the word "prediction" applies in this analysis. Am I missinterpreting what you want? Is the issue-title accurate?

* This is the kind of anlaysis that I think an intern could start doing right now. Later, the code will have nicer functions and more features, but it would be great to have someone closer to the biology of these trees checking for scientific correctness -- regardlesss of the implementation in code.

**Comment by teixeirak** [comment] 2019-03-14 15:34
To clarify, by `biomass` do you mean total aboveground biomass from allodb? Whereas 'agb' is what's currently in the SCBI data table (calculated based off tropical allometry)?

**Comment by teixeirak** [comment] 2019-03-14 15:35
@gonzalezeb, assuming my interpretation there is correct, it appears that our equations for Platanus occidentalis and Nyssa sylvatica are off. Can you please check?

**Comment by maurolepore** [comment] 2019-03-14 15:39
> To clarify, by biomass do you mean total aboveground biomass from allodb? Whereas 'agb' is what's currently in the SCBI data table (calculated based off tropical allometry)?

Yes,

`biomass`: Calculated based on equations from allodb
`agb`: From the `agb` column in the SCBI data -- presumably calculated using equations for tropical species. Should be a good reference against which to compare the results using equations from allodb.

**Comment by teixeirak** [comment] 2019-03-14 15:50
Okay, I take it your example plot (# 1 below) would look more like the example I sent (# 2 below) when you include larger diameters (but exclude Nyssa sylvatica and Platanus occidentalis)? 
@gonzalezeb, plotting on the scale of # 1 below highlights huge divergence in predicted biomass for trees of ~50cm, both based on our allometries and the tropical allometries.  Does this make sense? It's hard to tell which species are in which group. Oaks are definitely in the higher-biomass group, and maybe pines in the lower group? I'd assume this is driven by wood density?

![image](https://user-images.githubusercontent.com/6355854/54370529-24c82280-464e-11e9-9a9c-60dc97285da6.png)

![image](https://user-images.githubusercontent.com/6355854/54370546-2d205d80-464e-11e9-8189-73c37674f0e3.png)

**Comment by teixeirak** [comment] 2019-03-14 16:03
Regarding review of these equations, I do not see that as the role for an intern. @maurolepore, you've already produced code to generate these plots. @gonzalezeb and I (to a lesser extent) should be the ones reviewing these plots to make sure output looks reasonable. In the longer term, issue #16 calls for code to flag equations that give unreasonable output. Right now/ to start (and maybe this is all we'll ever want), it may be worth writing a very simple script where each equation will be evaluated at ~3 dbh values (e.g., 1 cm, 50 cm, 100 cm; counting only those within range of the equation's DBH limits) and equations flagged if they don't fall within a range that we consider reasonable for that size (@gonzalezeb could provide guidance on those threshholds).

**Comment by maurolepore** [comment] 2019-03-14 16:38
>  huge divergence in predicted biomass for trees of ~50cm, both based on our allometries and the tropical allometries. ...  It's hard to tell which species are in which group. 

Good point. Here I added a reference to tell those species appart.


![image](https://user-images.githubusercontent.com/5856545/54374612-e171b200-4655-11e9-8cff-7f9915815475.png)

![image](https://user-images.githubusercontent.com/5856545/54374646-f0f0fb00-4655-11e9-9a17-74fe70537a97.png)

![image](https://user-images.githubusercontent.com/5856545/54374679-02d29e00-4656-11e9-8f4a-4ae116faafd9.png)

**Comment by maurolepore** [comment] 2019-03-14 16:46
> Right now/ to start (and maybe this is all we'll ever want), it may be worth writing a very simple script where each equation will be evaluated at ~3 dbh values (e.g., 1 cm, 50 cm, 100 cm; counting only those within range of the equation's DBH limits) and equations flagged if they don't fall within a range that we consider reasonable for that size (@gonzalezeb could provide guidance on those threshholds)

Good idea. I'll follow up at https://github.com/forestgeo/fgeo.biomass/issues/22

**Comment by gonzalezeb** [comment] 2019-03-14 17:08
I see the problems in the equations for Platanus, Nyssa and two others.. I am fixing it.. you are just to fast for me!

**Comment by teixeirak** [comment] 2019-03-14 17:21
Thanks for the plot, @maurolepore!  From this, its mainly the hickories and Tilia that are low. This doesn't make much sense, as their wood density tends to be on the high end.  @gonzalezeb, what do you think?

**Comment by maurolepore** [comment] 2019-03-15 15:42
> equations flagged if they don't fall within a range that we consider reasonable for that size (@gonzalezeb could provide guidance on those threshholds)

How about creating that reasonable range from the deviation from the curve fit to `dbh` vs the preexisting  `agb` value for for each species? 

Althought the preexisting `agb` was calculated for tropical trees, the plots above show that it is likely close enough to the `biomass` we should get from allodb -- that is, enough to pick obvious errors in the equations.

**Comment by teixeirak** [comment] 2019-03-15 15:46
We can try that as a rough first approximation.

**Comment by maurolepore** [comment] 2019-03-15 17:07
> I see the problems in the equations for Platanus, Nyssa and two others...

@gonzalezeb, can you confirm this are the changes you did? I still don't see changes in Platanus, Nyssa, Are those yet to come or am I missing something?

``` r
library(tidyverse)

edited_eqn <- c("333c34" , "e9d686")

allodb::master() %>% 
  filter(equation_id %in% edited_eqn) %>% 
  select(equation_id, site, species, equation_allometry)
#> Joining `allodb::equations` with `allodb::sitespecies` by 'equation_id'.
#> Then joining with `allodb::sites_info` by 'site'.
#> # A tibble: 10 x 4
#>    equation_id site              species             equation_allometry    
#>    <chr>       <chr>             <chr>               <chr>                 
#>  1 333c34      Lilly Dicky       Robinia pseudoacac~ 4.06014*(dbh^2)^1.052~
#>  2 333c34      SCBI              Robinia pseudoacac~ 4.06014*(dbh^2)^1.052~
#>  3 333c34      UMBC              Gleditsia triacant~ 4.06014*(dbh^2)^1.052~
#>  4 333c34      UMBC              Robinia pseudoacac~ 4.06014*(dbh^2)^1.052~
#>  5 333c34      Michigan Big Woo~ Robinia pseudoacac~ 4.06014*(dbh^2)^1.052~
#>  6 e9d686      Lilly Dicky       Robinia pseudoacac~ 0.77201*(dbh^2)^1.412~
#>  7 e9d686      SCBI              Robinia pseudoacac~ 0.77201*(dbh^2)^1.412~
#>  8 e9d686      UMBC              Gleditsia triacant~ 0.77201*(dbh^2)^1.412~
#>  9 e9d686      UMBC              Robinia pseudoacac~ 0.77201*(dbh^2)^1.412~
#> 10 e9d686      Michigan Big Woo~ Robinia pseudoacac~ 0.77201*(dbh^2)^1.412~
```

Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment] 2019-03-15 17:13
I haven't included them because it required a deeper search.. I am working them now.

**Comment by gonzalezeb** [comment] 2019-03-15 20:05
I made changes for Platanus and Nyssa (and I am reviewing others, ie. quercus velutina, caryas, etc).

**Comment by maurolepore** [comment] 2019-03-15 20:12
Thanks @gonzalezeb,

 Platanus and Nyssa are looking good.

![image](https://user-images.githubusercontent.com/5856545/54459166-37208a00-473c-11e9-98d4-cc8a29eafe16.png)
.
.

There seem to be a six outliers where calculated `biomass` is much higher than the reference `agb`. Let me know if anything jumps into your eyes

![image](https://user-images.githubusercontent.com/5856545/54459256-86ff5100-473c-11e9-8444-4f71afa80901.png)

![image](https://user-images.githubusercontent.com/5856545/54459233-6d5e0980-473c-11e9-9e4e-078abfc68a42.png)

.
.

But after excluding those potencial outliers the general picture looks reasonable.

![image](https://user-images.githubusercontent.com/5856545/54459380-e8bfbb00-473c-11e9-8616-7beb2c41d1e6.png)

**Comment by gonzalezeb** [comment] 2019-03-15 20:55
But look at this when a test the largest quercus velutina  at scbi
> dbh=153/2.54  #cm to lbs
> 2.1457*(dbh^2.503) #our equation
[1] 61172.03 #results in lbs
[1] 27742.42 #result in kg

**Comment by gonzalezeb** [comment] 2019-03-15 21:01
Same for eq c70dea
> dbh=153/2.54
> 10^(1.00005+2.10621*(log10(dbh)))			 	
[1] 56079.5  #in lbs
> 56079.5/2.205
[1] 25432.88  #in kg

**Comment by teixeirak** [comment] 2019-03-15 21:11
We need to understand what’s going on with that divergence among species in Mauro’s figure. Why are some species so much higher than others?

On Mar 15, 2019, at 5:01 PM, Erika Gonzalez-Akre <notifications@github.com<mailto:notifications@github.com>> wrote:


Same for eq c70dea

dbh=153/2.54
10^(1.00005+2.10621*(log10(dbh)))
[1] 56079.5 #in lbs
56079.5/2.205
[1] 25432.88 #in kg

**Comment by maurolepore** [comment] 2019-03-15 21:13
> Why are some species so much higher than others?

Just noting that it seems that it is not a problem of allodb equations, as the preexisting `agb` (shown in grey) follows the same pattern.

**Comment by teixeirak** [comment] 2019-03-15 21:26
I wouldn’t put much stake in the calculations using the tropical equation. Also, do the same species separate out that way in the tropical calculations, or is it a different set? 

We need to understand what drives that difference (mathematically) and whether it makes sense biologically. From my initial review, it doesn’t seem to (many of the lower biomass species have higher wood density.) Erika, what is the source of these equations?

**Comment by maurolepore** [comment] 2019-03-15 21:36
> do the same species separate out that way in the tropical calculations, or is it a different set?

I think so. See the grey reference here:


![image](https://user-images.githubusercontent.com/5856545/54463213-b451fc00-4748-11e9-8bc4-1da727ed9f4d.png)

**Comment by gonzalezeb** [comment] 2019-03-17 15:24
Those equations are from Jenkins 2004.

**Comment by maurolepore** [comment] 2019-03-17 18:25
1. Is this it? https://www.fs.fed.us/ne/durham/4104/papers/ne_gtr319_jenkins_and_others.pdf

2. Are those the equations allodb will use as generic equations to fall back when species+site-specific equations are not available? 

3. Are they already in allodb?

**Comment by gonzalezeb** [comment] 2019-03-17 19:21
1. Yes, that's the pub. 
2. (and 3) Many of them already are in allodb. Not all equations are generic, many are species specific allometries (and a few genus specific), we consider them the best available (or 'Expert' selected) for a particular site. Note that many sites (specially in North America) don't have site specific equations, there are actually very few sites with those kind (still not in allodb).

**Comment by maurolepore** [comment] 2019-03-17 19:37
I see. Then the grey and black dots should overlap even more than they do, right?

**Comment by teixeirak** [comment] 2019-03-18 15:52
@maurolepore, could you please verify that you're plotting predictions for each species using only the equations specified for the size range?

**Comment by maurolepore** [comment] 2019-03-18 16:02
> [Are you] plotting predictions for each species using only the equations specified for the size range?

No, not yet.

https://github.com/forestgeo/allodb/issues/73#issuecomment-472918150
![image](https://user-images.githubusercontent.com/5856545/54544275-9fa67b80-4975-11e9-929e-4c5f4d883a1e.png)

**Comment by teixeirak** [comment] 2019-03-18 16:07
Okay, that might explain this divergence where some species (Liriodendron, Quercus) have much higher biomass at a given size than others (Juglans, Carya). From examining the Liriodendron equations, it looks like that might be going on there (although I get even more radical divergence). Could you please make it high priority to implement this restriction? It's pointless for us to try to evaluate the equations using these plots before that's done.

**Comment by teixeirak** [comment] 2019-03-18 16:10
One thing about these plots remains very confusing. The grey dots indicate calculations from the tropical equations (based on wood density), correct? Tulip poplar has a much lower wood density than others (Quercus, Juglans, Carya), and I've confirmed that this is accurately reflected in the CTFS wood density data set used to calculate these values, so it doesn't make sense that it would have higher biomass at a given DBH.

**Comment by maurolepore** [comment] 2019-03-18 16:27
> Could you please make it high priority to implement this restriction?

Sure, I understand that getting accurate `biomass` values is high priority. But first I need to fully understand why some equations can't be computed at all. Erika just closed an issue that should make things much better (https://github.com/forestgeo/allodb/issues/78).

> It's pointless for us to try to evaluate the equations using these plots before that's done.

I agree that discussing the precision of `biomass` values right now is like trying to run before we can walk. I'm sorry if my comment https://github.com/forestgeo/allodb/issues/73#issuecomment-472918150 wasn't clear. 

However this thread has been super useful. These are some of the lessons we learned:

* We identified obvious errors in some equations; 
* We discussed different visualizations of the data you would like; 
* I leaned where the `agb` values in grey come from; I identified a bunch of species with no `biomass` value at all which let to removing redundant columns.

I highlight these lessons because I need you to help me help you. The more you engage in the process, the faster we will all move.

**Comment by maurolepore** [comment] 2019-03-18 16:37
> The grey dots indicate calculations from the tropical equations (based on wood density), correct? 

Apparently not. 

I thought so, but then Erika suggested that the `agb` column in the SCBI data  (see below) -- comes from [this paper](https://www.fs.fed.us/ne/durham/4104/papers/ne_gtr319_jenkins_and_others.pdf) on allometries for North America -- not from the paper on equations for tropical trees.

``` r
library(tidyverse)
#> Warning: package 'purrr' was built under R version 3.5.3

fgeo.biomass::scbi_tree1 %>% 
  select(agb, everything())
#> # A tibble: 40,283 x 20
#>        agb treeID stemID tag   StemTag sp    quadrat    gx    gy DBHID
#>      <dbl>  <int>  <int> <chr> <chr>   <chr> <chr>   <dbl> <dbl> <int>
#>  1 1.59e-3      1      1 10079 1       libe  0104     3.70  73       1
#>  2 9.74e-4      2      2 10168 1       libe  0103    17.3   58.9     3
#>  3 9.88e-4      3      3 10567 1       libe  0110     9    197.      5
#>  4 1.24e-1      4      4 12165 1       nysy  0122    14.2  428.      7
#>  5 5.12e-2      5      5 12190 1       havi  0122     9.40 436.      9
#>  6 1.45e-3      6      6 12192 1       havi  0122     1.30 434      13
#>  7 7.05e-3      7      7 12212 1       unk   0123    17.8  447.     15
#>  8 9.65e-3      8      8 12261 1       libe  0125    18    484.     17
#>  9 6.25e-3      9      9 12456 1       vipr  0130    18    598.     19
#> 10 5.41e-4     10     10 12551 1       astr  0132     5.60 628.     22
#> # ... with 40,273 more rows, and 10 more variables: CensusID <int>,
#> #   dbh <dbl>, pom <chr>, hom <dbl>, ExactDate <chr>, DFstatus <chr>,
#> #   codes <chr>, nostems <dbl>, date <dbl>, status <chr>
```

Created on 2019-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by teixeirak** [comment] 2019-03-18 16:49
Given the uncertainty about the sources of the grey dots, let's just ignore those data.

**Comment by teixeirak** [comment] 2019-03-18 16:49
Please alert me once we're correctly plotting all equations as intended, and I'll return to the review.

**Comment by gonzalezeb** [comment] 2019-03-18 18:03
> I thought so, but then Erika suggested that the agb column in the SCBI data (see below) -- comes from this paper on allometries for North America -- not from the paper on equations for tropical trees.

Sorry, my mistake.. I though you were asking for the equations from allodb. The `agb` in the scbi data (data that comes from the ctfs main database) is calculated based on tropical allometries using an old code in the old CTFS R package (as explained [here](http://ctfs.si.edu/Public/CTFSRPackage/index.php/web/topics/biomass~slash~biomass.CTFSdb.r/AGB.ind)).

On the metadata for the scbi.full or scbi.stem tables ([here](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_main_census/metadata)), agb is described as:
`agb`_Above-ground-biomass of all stems on the tree, in Mg (= metric tons or 106 g). Note that agb=0 for dead trees._

**Comment by maurolepore** [comment] 2019-03-18 22:21
@gonzalezeb,

FYI, in [this update](https://github.com/forestgeo/fgeo.biomass/blob/master/.buildignore/dbh-vs-biomass.md#plot-dbh-vsbiomass-by-species), the `biomass` of _Liriodendron sp._ appears too high, which Krista suggests might be solved once I support dbh-specific equations. Also see a few suspicious points over 40,000 [kg].

The most important accomplishment of today is that I can now explain all missing `biomass` values. I'm ready to move on to more sophisticated features that should result in more precise `biomass`.

**Comment by maurolepore** [comment] 2019-03-19 00:42
Regarding _Lliriodendron tulipifera_, I wonder if the issue may be one of units. That may explain such a difference -- where the resulting `biomass` values` greater not by a little but by orders of magnitude.

**Comment by teixeirak** [comment] 2019-03-19 12:42
Incorrect units could definitely cause this kind of problem, but I believe @gonzalezeb already checked that.

**Comment by gonzalezeb** [comment] 2019-03-19 13:44
Interestingly, I did n't change that equation in my recent fixes so not sure why those large biomass biomass values didn't show before. 
At the same time, I just confirmed that equation 94f593 (the one giving those bad values) is incorrect so I will review it.

**Comment by teixeirak** [comment] 2019-03-19 13:45
It wouldn't have shown up bad before if it was being applied only within the specified DBH range.

**Comment by maurolepore** [comment] 2019-03-19 15:55
Thanks @gonzalezeb, it's now looking much better. It will continue to improve as we support the more features.

![image](https://user-images.githubusercontent.com/5856545/54621241-d34cd880-4a3d-11e9-927d-10ee7064f0fa.png)

**Comment by maurolepore** [comment] 2019-03-20 21:50
@gonzalezeb, 

We now support dbh-specific equations. There is a new update here http://bit.ly/demo-dbh-vs-biomass

Please see https://github.com/forestgeo/fgeo.biomass/issues/27

**Comment by teixeirak** [comment] 2019-03-20 22:12
Wonderful! At a first pass, this looks much more like what I expected. At a first pass, I don't see any problems.

**Comment by maurolepore** [comment] 2019-03-21 20:48
We still don't support generic equations. On one branch of the project I temporarily removed generic equations completely (discussion at https://github.com/forestgeo/allodb/issues/72). 

Removing generic equations should produce more accurate `biomass` estimates for the species we have equations for, but it comes at the cost of loosing some species.

Compare (@teixeirak):

* Without generic equaitons: [branch](https://github.com/forestgeo/fgeo.biomass/blob/allo72_generic/.buildignore/dbh-vs-biomass.md#plot-dbh-vsbiomass-by-species).

* With generic equations http://bit.ly/demo-dbh-vs-biomass

**Comment by teixeirak** [comment] 2019-03-22 16:03
There are a lot of species that rely on generic equations. What do we need to be able to handle them? Please let me know if there are any barriers you face in order to incorporate them (other than just time to work on this).

**Comment by maurolepore** [comment] 2019-03-22 23:17
`allo_find()` now automatically prefers expert equations but falls back to generic equations for matching species. This change isn't yet in the master branch but will be merged soon. For now you can see it in action on [this branch](https://github.com/forestgeo/fgeo.biomass/blob/allo72_generic/.buildignore/dbh-vs-biomass.md#plot-dbh-vsbiomass-by-species).

Notice that trees which species is given as _Genus sp._ can't find a matching species on allodb. We need to support that feature (https://github.com/forestgeo/fgeo.biomass/issues/30).

```R
allo_find(census_species)
#> Assuming `dbh` in [mm] (required to find dbh-specific equations).
#> * Matching equations by site and species.
#> * Refining equations according to dbh.
#> * Using generic equations where expert equations can't be found.
#> Warning:   Can't find equations matching these species:
#>   acer sp, carya sp, crataegus sp, fraxinus sp, juniperus virginiana, quercus prinus, quercus sp, ulmus sp, unidentified unk
#> Warning: Can't find equations for 17132 rows (inserting `NA`).

```

**Comment by teixeirak** [comment] 2019-03-22 23:55
Great! 

There may be cases where “Genus sp.” would have a site-specific equation. That would be something for Erika to comment on / deal with. For now it will be fine for them to fall back on generic equations for any site (which of course remain to be entered, and I’d be happy to enter some examples if needed).

**Comment by maurolepore** [comment] 2019-03-25 20:36
> There may be cases where “Genus sp.” would have a site-specific equation. 

I see some examples of this already. 

``` r
library(tidyverse)
library(allodb)

master() %>% 
  select(site, species, equation_group) %>% 
  filter(equation_group == "Generic") %>% 
  filter(str_detect(species, " sp.$")) %>% 
  distinct()
#> Joining `equations` and `sitespecies` by 'equation_id'; then `sites_info` by 'site'.
#> # A tibble: 15 x 3
#>    site           species       equation_group
#>    <chr>          <chr>         <chr>         
#>  1 serc           Ligustrum sp. Generic       
#>  2 lilly dicky    Crataegus sp. Generic       
#>  3 serc           Vaccinium sp. Generic       
#>  4 tyson          Crataegus sp. Generic       
#>  5 umbc           Crataegus sp. Generic       
#>  6 harvard forest Crataegus sp. Generic       
#>  7 serc           Quercus sp.   Generic       
#>  8 yosemite       Salix sp.     Generic       
#>  9 wind river     Abies sp.     Generic       
#> 10 yosemite       Abies sp.     Generic       
#> 11 lilly dicky    Carya sp.     Generic       
#> 12 scbi           Carya sp.     Generic       
#> 13 serc           Carya sp.     Generic       
#> 14 tyson          Carya sp.     Generic       
#> 15 umbc           Carya sp.     Generic
```

> ... fall back on generic equations for any site ...  I’d be happy to enter some examples if needed

Okay, with two examples I should have enogh to build the logic.

**Comment by teixeirak** [comment] 2019-03-25 23:42
I will provide a couple examples soon.

**Comment by teixeirak** [comment] 2019-03-26 13:47
Should I put the examples in [this table](https://github.com/forestgeo/allodb/blob/master/data-raw/csv_database/sitespecies.csv)? That is, do edits go to the .csv files in raw data, as opposed to the R tables?  (Note that I just fixed a typo in that file, assuming that will make it into R tables.)

**Comment by maurolepore** [comment] 2019-03-26 14:25
If by "example" we mean a mock, then you may simpliy give me the name of a couple of allometries and tell me which sites and taxa they should match. I can create a toy dataset to build some code around.

If instead by "example" we mean something that is production ready (i.e. not a toy but something that can be really used), then certainly the files you want to edit live in the directory data-raw/csv_database/ (https://github.com/forestgeo/allodb/blob/master/data-raw/csv_database/). In this case you'll need to enter new rows in the `equations` table, each row with an `equation_id` from [this file](https://github.com/forestgeo/allodb/blob/master/data-raw/available_random_ids.csv) (please read [this short explanation](https://github.com/forestgeo/allodb/blob/master/data-raw/available_random_ids.md)), the taxa and corresponding allometry, and all other relevant information to complete the row. Also you will need to enter the exact same `equation_id` in the `sitespecies` table (because `equation_id` is the key linking the `sitespecies` with the `equations` table) along with the site and other relevant information to complete the row. Below is a short view of the most important columns in each of those two tables.

In this case we can tag your commits to make sure that Erika can later review them.


``` r
library(allodb)
library(tidyverse)

list(equations = equations, sitespecies = sitespecies) %>% 
  map(~ select(.x, matches("^site|^species|^equation|allometry$")))
#> $equations
#> # A tibble: 175 x 3
#>    equation_id equation_allometry                equation_form          
#>    <chr>       <chr>                             <chr>                  
#>  1 2060ea      10^(1.1891+1.419*(log10(dbh^2)))  10^(a+b*(log10(dbh^c)))
#>  2 a4d879      10^(1.2315+1.6376*(log10(dbh^2))) 10^(a+b*(log10(dbh^c)))
#>  3 c59e03      exp(7.217+1.514*log(dbh))         exp(a+b*log(dbh))      
#>  4 96c0af      10^(2.5368+1.3197*(log10(dbh)))   10^(a+b*(log10(dbh)))  
#>  5 529234      10^(2.0865+0.9449*(log10(dbh)))   10^(a+b*(log10(dbh)))  
#>  6 ae65ed      exp(-2.48+2.4835*log(dbh))        exp(a+b*log(dbh))      
#>  7 9c4cc9      10^(-1.326+2.762*(log10(dbh)))    10^(a+b*(log10(dbh)))  
#>  8 7f7777      exp(-2.5095+2.5437*log(dbh))      exp(a+b*log(dbh))      
#>  9 cf733d      exp(5.67+1.97*log(dbh))           exp(a+b*log(dbh))      
#> 10 f08fff      exp(-2.2118+2.4133*log(dbh))      exp(a+b*log(dbh))      
#> # ... with 165 more rows
#> 
#> $sitespecies
#> # A tibble: 772 x 6
#>    site    species    species_code equation_group equation_id equation_taxa
#>    <chr>   <chr>      <chr>        <chr>          <chr>       <chr>        
#>  1 Lilly ~ Acer rubr~ 316          Expert         7c72ed      Acer rubrum  
#>  2 Lilly ~ Acer rubr~ 316          Expert         2060ea      Acer rubrum  
#>  3 Lilly ~ Acer sacc~ 318          Expert         a4d879      Acer sacchar~
#>  4 Lilly ~ Amelanchi~ 356          Expert         c59e03      Amelanchier  
#>  5 Lilly ~ Amelanchi~ 356          Expert         96c0af      Amelanchier  
#>  6 Lilly ~ Amelanchi~ 356          Expert         529234      Amelanchier  
#>  7 Lilly ~ Asimina t~ 367          Generic        ae65ed      Mixed hardwo~
#>  8 Lilly ~ Carpinus ~ 391          Generic        ae65ed      Mixed hardwo~
#>  9 Lilly ~ Carya alba 409          Expert         9c4cc9      Carya        
#> 10 Lilly ~ Carya cor~ 402          Expert         9c4cc9      Carya        
#> # ... with 762 more rows
```

Created on 2019-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by teixeirak** [comment] 2019-03-26 14:56
I added some (real) generic equation entries to the sitespecies table ([this commit](https://github.com/forestgeo/allodb/commit/841f1927e4a7ab9546b365e7eadc6a780294dcbe)). These were equations that were already in the database, not totally new equations. For reasons relating to issue #85, I haven't checked whether they would represent the range of scenarios you may encounter, or even ever be called upon with the current set of ForestGEO sites. You can start with that and let me know if you need others.

**Comment by maurolepore** [comment] 2019-03-26 16:12
Your commit is now tagged -- meaning that it's easy to find and revert

![image](https://user-images.githubusercontent.com/5856545/55013860-5c28be80-4fc0-11e9-90b9-a0ab636bfcae.png)

**Comment by maurolepore** [comment] 2019-04-04 20:36
We now support shrubs. You can see the updated biomass analysis at  http://bit.ly/demo-dbh-vs-biomass

After you comments I should be able to soon close https://github.com/forestgeo/allodb/issues/41
I'm only unsure about how to interpret `dbh_min_cm` when using shrub equations which independent variable is `dba`. My question is at https://github.com/forestgeo/allodb/issues/41#issuecomment-480003361

**Comment by maurolepore** [comment] 2019-04-09 23:35
@teixeirak, and @gonzalezeb, FYI:

* We now have a much simpler interface. 
* The analysis of `dbh` versus `biomass` is now on [README](https://github.com/forestgeo/fgeo.biomass/blob/master/README.md)

**Comment by gonzalezeb** [comment] 2021-02-19 23:28
This issue is handle by the functions [get_biomass](https://github.com/forestgeo/allodb/blob/master/R/get_biomass.R) and [illustrate_allodb](https://github.com/forestgeo/allodb/blob/master/R/illustrate_allodb.R).

**Closed by gonzalezeb** 2021-02-19 23:28 UTC
Labels: needs-review, priority high, wip
