### ISSUE TITLE
errors in get_biomass

### ISSUE THREAD

**Issue by ValentineHerr** [forestgeo/allodb#105] opened 2020-04-09 18:33 UTC
`, with = FALSE` in [this line of code](https://github.com/forestgeo/allodb/blob/8cad6209fb2aff7e34300f714b740c43bfeaf276/R/get_biomass.R#L18) is generating an error for me.

**Comment by ValentineHerr** [comment] 2020-04-09 18:41
it looks like these columns:
- lat,
- long,
- elev_m,
- dbh_unit_CF,
- output_units_CF,
- r_squared

are supposed to be in `equations` as [these lines](https://github.com/forestgeo/allodb/blob/8cad6209fb2aff7e34300f714b740c43bfeaf276/R/get_biomass.R#L26-L38) are tying to pull them from there, but they don't seem to exist in `equations`

**Comment by cpiponiot** [comment] 2020-04-09 22:11
they should be in `equations`, when I try this: 
`load("data/equations.rda");
colnames(equations)`
all the columns you mentioned appear

**Comment by cpiponiot** [comment] 2020-04-09 22:18
> `, with = FALSE` in [this line of code](https://github.com/forestgeo/allodb/blob/8cad6209fb2aff7e34300f714b740c43bfeaf276/R/get_biomass.R#L18) is generating an error for me.

this should be fixed now (I added a line to load the `data.table` package in the function).
Whether we should use this package or not is another question, I could try 2 versions of the function, with or without it, and see if there is a big gain in running time that justifies using `data.table`

**Comment by ValentineHerr** [comment] 2020-04-10 13:30
@cpiponiot 
what do you get when running 
`library(allodb)`
`data("equations")`
`names(equations)`
?

For me, equations has much fewer columns when I load the package than when I take directly from the repo... weird!

**Comment by ValentineHerr** [comment] 2020-04-10 13:43
There must be a missing dependency as I get the following error when running `get_biomass()`

`Error in set(taxo_weight_census, i = which(is.na(taxo_weight_census[[col]])),  : 
  could not find function "set"`

**Comment by cpiponiot** [comment] 2020-04-10 14:17
Have you pulled the commits from yesterday? The function `set()` is from the `data.table` package too, which should be loaded inside the `get_biomass()` function now

**Comment by ValentineHerr** [comment] 2020-04-10 14:43
Oh right, sorry for that.

I am trying to re-install allodb via `remotes::install_github('forestgeo/allodb')` to update it but I am getting errors.... I'll try to figure out what is going on.

**Comment by cpiponiot** [comment] 2020-04-10 14:47
Yes, me too, I guess for now it's best to just use it directly from the repo (probably some formatting issue, we can figure this one later)

**Comment by ValentineHerr** [comment] 2020-04-10 14:48
First, FYI,  I get this warning:

`NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'allodb/data/koppenMatrix.rda'  'allodb/data/koppenRaster.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'allodb/data/taxo_weight.rda'  'allodb/data/temp_censusTaxa.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'allodb/data/temp_equationTaxa.rda'`

I am runninf this version of R:  R version 3.6.2 (2019-12-12)

**Comment by ValentineHerr** [comment] 2020-04-10 14:48
> Yes, me too, I guess for now it's best to just use it directly from the repo (probably some formatting issue, we can figure this one later)

ok

**Comment by cpiponiot** [comment] 2020-04-10 14:51
> First, FYI, I get this warning:
> 
> `NB: this package now depends on R (>= 3.5.0) WARNING: Added dependency on R >= 3.5.0 because serialized objects in serialize/load version 3 cannot be read in older versions of R. File(s) containing such objects: 'allodb/data/koppenMatrix.rda' 'allodb/data/koppenRaster.rda' WARNING: Added dependency on R >= 3.5.0 because serialized objects in serialize/load version 3 cannot be read in older versions of R. File(s) containing such objects: 'allodb/data/taxo_weight.rda' 'allodb/data/temp_censusTaxa.rda' WARNING: Added dependency on R >= 3.5.0 because serialized objects in serialize/load version 3 cannot be read in older versions of R. File(s) containing such objects: 'allodb/data/temp_equationTaxa.rda'`
> 
> I am runninf this version of R: R version 3.6.2 (2019-12-12)

Yeah okay I see what the issue is, it'll be easy to fix I think. It's just that the class of the objects is not supported by base R, but I just have to save them in another format.

**Comment by gonzalezeb** [comment] 2020-05-19 14:05
get_biomass is working well now.

**Closed by gonzalezeb** 2020-05-19 14:05 UTC
